# Generated by Django 5.0.1 on 2024-01-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0006_alter_orderitem_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
