# Generated by Django 5.0.1 on 2024-01-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0007_productvariant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='eComm_App.OrderItem', to='eComm_App.productvariant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eComm_App.productvariant'),
        ),
    ]
