# Generated by Django 5.0.1 on 2024-01-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0008_alter_order_products_alter_orderitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='eComm_App.OrderItem', to='eComm_App.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eComm_App.product'),
        ),
    ]
