# Generated by Django 5.0.1 on 2024-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0009_alter_order_products_alter_orderitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
