# Generated by Django 5.0.1 on 2024-01-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0010_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
    ]
