# Generated by Django 5.0.1 on 2024-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0015_order_delivery_address_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, default='Will be Arriving Soon', null=True),
        ),
    ]
