# Generated by Django 5.0.1 on 2024-02-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0021_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
