# Generated by Django 5.0.1 on 2024-05-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0023_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_ratings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
