# Generated by Django 5.0.1 on 2024-05-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0024_alter_customer_photo_alter_product_no_of_ratings_and_more'),
        ('eComm_App', '0024_alter_product_no_of_ratings_alter_product_ratings'),
    ]

    operations = [
    ]
