# Generated by Django 5.0.1 on 2024-05-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eComm_App', '0025_merge_20240519_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
